apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uhwqgi149-nodejs-gitops
  description: This is GitOps manifest for uhwqgi149-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=uhwqgi149-nodejs
    backstage.io/kubernetes-id: uhwqgi149-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uhwqgi149-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uhwqgi149-nodejs
